name: Release
on:
  workflow_run:
    workflows:
      - Build-Angular
    types:
      - completed
      - success
  
jobs:
  Test:
    runs-on: ubuntu-latest
    environment:
      name: 'Test'
      url: ${{ steps.deploy-to-webapp-test.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v2
      - uses: alextompkins/download-prior-artifact@v1
        with:
           name: node-app
           #path: path/to/artifact
      - name: Display structure of downloaded files
        run: ls -R
           
      - name: Print workspace directory
        run: |
          echo "Workspace directory: ${{ github.workspace }}"
          echo "Contents of workspace:"
          ls -a ${{ github.workspace }}/angular1
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp-Test
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gitaction'
          slot-name: 'Test'
          publish-profile: ${{ secrets.TEST }}
          package: ${{ github.workspace }}     
          
  Production:
    needs: Test
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gitaction'
          slot-name: 'Production'
          publish-profile: ${{ secrets.GITHUBACTION }}
          package: ${{ github.workspace }}
