
name: Release
on:
  workflow_run:
    workflows:
      - Build-Angular
    types:
      - completed

jobs:
  deploy:
    runs-on: windows-2022
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gitaction'
          slot-name: 'Production'
          publish-profile: ${{ secrets.GITHUBACTION }}
          package:  ${{ github.workspace }}
          
  deploy-prod1:
    runs-on: windows-2022
    environment:
      name: 'Production 1'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gitaction'
          slot-name: 'Production 1'
          publish-profile: ${{ secrets.GITHUBACTION }}
          package:  ${{ github.workspace }}        
