name: Release
on:
  workflow_run:
    workflows:
      - Build-Angular
    types:
      - completed
      - success

jobs:
  Test:
    runs-on: ubuntu-latest
    environment:
      name: 'Test'
      url: ${{ steps.deploy-to-webapp-test.outputs.webapp-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: node-app
          path: ${{ github.workspace }}/**/*.zip
                 
      - name: Print dist folder files
        run: |
          echo "List of files in dist/angular1 folder:"
          ls -a ${{ github.workspace }}/angular1/dist/angular1
          
      - name: Print workspace contents
        run: |
          echo "Workspace directory: ${{ github.workspace }}"
          echo "Contents of workspace:"
          ls -a ${{ github.workspace }}/angular1/dist

          
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp-Test
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gitaction'
          slot-name: 'Test'
          publish-profile: ${{ secrets.TEST }}
          package: ${{ github.workspace }}     
          
  Production:
    needs: Test
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gitaction'
          slot-name: 'Production'
          publish-profile: ${{ secrets.GITHUBACTION }}
          package: ${{ github.workspace }}
