
name: Release
on:
  workflow_run:
    workflows:
      - Build-Angular
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact checkout
        uses: actions/checkout@v2
        
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
          path: node-app
          
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gitaction'
          slot-name: 'Production'
          publish-profile: ${{ secrets.GITHUBACTION }}
          package:  ${{ github.workspace }}/*
