name: Release
on:
  workflow_run:
    workflows:
      - Build-Angular
    types:
      - completed
      - success
  
jobs:
  Dev:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    environment:
      name: 'Dev'
      url: ${{ steps.deploy-to-webapp-dev.outputs.webapp-url }}

    steps:
      - name: Print Head Ref
        run: echo "${{ github.event.workflow_run.head_branch }}"
        
      - name: Download last artifact
        uses: blablacar/action-download-last-artifact@master
        with:
          name: node-app
      - name: Display structure of downloaded files
        run: ls -R
           
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp-Dev
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gitaction'
          slot-name: 'Dev'
          publish-profile: ${{ secrets.Dev }}
          package: ${{ github.workspace }}/angular1
          
  Test:
    if: github.ref_name == 'dev1'
    runs-on: ubuntu-latest
    environment:
      name: 'Test'
      url: ${{  steps.deploy-to-webapp-test.outputs.webapp-url  }}

    steps:
      - name: Print Head Ref
        run: echo "${{ github.ref_name }}"
        
      - name: Download last artifact
        uses: blablacar/action-download-last-artifact@master
        with:
          name: node-app
      - name: Display structure of downloaded files
        run: ls -R
           
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp-Test
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gitaction'
          slot-name: 'Test'
          publish-profile: ${{ secrets.TEST }}
          package: ${{ github.workspace }}/angular1   
          
  Production:
    needs: [Test]
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download last artifact
        uses: blablacar/action-download-last-artifact@master
        with:
         name: node-app
      - name: Display structure of downloaded files
        run: ls -R
          
      #- uses: trstringer/manual-approval@v1
        #with:
          #secret: ${{ github.TOKEN }}
          #approvers: hem1232
          #minimum-approvals: 1
          #issue-title: "Deploying v1.3.5 to prod from staging"
          #issue-body: "Please approve or deny the deployment of version v1.3.5."
          #exclude-workflow-initiator-as-approver: false
          #additional-approved-words: ''
          #additional-denied-words: ''
          
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gitaction'
          slot-name: 'Production'
          publish-profile: ${{ secrets.GITHUBACTION }}
          package: ${{ github.workspace }}/angular1
