
name: Release
on:
  workflow_run:
    workflows:
      - Build-Angular
    types:
      - completed

jobs:
  Dev:
    runs-on: windows-2022
    environment:
      name: 'Test'
      url: ${{ steps.deploy-to-webapp-test.outputs.webapp-url }}

    steps:
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp-Test
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gitaction'
          slot-name: 'Test'
          publish-profile: ${{ secrets.TEST }}
          package:  ${{ github.workspace }}     
          
  Production:
    runs-on: windows-2022
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gitaction'
          slot-name: 'Production'
          publish-profile: ${{ secrets.GITHUBACTION }}
          package:  ${{ github.workspace }}       
