name: UIBUILD
on:
  workflow_call:
   inputs:
      config-path:
        required: true
        type: string
      working-dir:
        type: string
   #secrets:
      #token:
        #required: true
     
jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: https://gpo.jfrog.io/gpo/api/npm/npm-local/
          JF_ACCESS_TOKEN: ${{ secrets.JFROG }}

      - run: |
         export SERVER_ID="test"
         jf c add $SERVER_ID --url=https://gpo.jfrog.io/gpo/api/npm/npm-local/ --access-token=${{ secrets.JFROG }} --interactive=false
         
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
           node-version: '16.x'
           
      - name: Install dependencies
        working-directory: angular1
        run: npm ci
        env:
           NODE_AUTH_TOKEN: ${{secrets.JFROG}}
           
      - name: Build Angular app
        working-directory: ${{ inputs.working-dir }}
        run: ng build --prod

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./angular1/dist
          retention-days: 1
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
          
      - name: Debug workspace
        run: |
          echo "Workspace directory: ${{ github.workspace }}"
          echo "Contents of workspace:"
          ls -a ${{ github.workspace }}
          
      - name: Print dist folder files
        run: |
          echo "List of files in dist/angular1 folder:"
          ls -a ${{ github.workspace }}/angular1/dist/angular1
           
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}
